services:
  gestionale:
    build: .
    container_name: gestionale_magazzino
    ports:
      - "8550:8550"
    volumes:
      - db_data:/app/app.db
    restart: unless-stopped
    environment:
      - DOCKER=1

volumes:
  db_data: